name: Terraform plan (Pull request commenter)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform bootstrap
        uses: ./.github/actions/terraform_bootstrap
        with:
          terraform_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Display
        run: echo "Success!"

      - name: Terraform plan
        env:
          # no tfvars within runners. Add variables in repo var within github.
          TF_VAR_subnet_config: ${{ vars.TF_VAR_subnet_config }}
        run: |
          terraform plan -no-color -out=plan_result

      - name: Convert plan_result into text
        run: |
          terraform show -no-color plan_result > plan.txt

      - name: PR commenter
        uses: peter-evans/create-or-update-comment@v5
        with:
          # Action that writes or modifies anything in GitHub requires authentication.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Get the PR number of the PR triggered this workflow.
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ðŸ“Œ Terraform Plan Result
            ```
            $(cat plan.txt)
            ```

