# Testing and performing terraform plan
name: Terraform testing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Format
        run: terraform fmt

      - name: Validate
        run: terraform validate

      - name: Terraform Initialization
        run: terraform init
      
      - name: Display
        run: echo "It worked!"