# Testing and performing terraform plan
name: Terraform testing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform bootstrap
        uses: ./.github/actions/terraform_bootstrap
        with:
          terraform_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0

      - name: Initialize  TFLint
        # Downloads AWS plugin. (.tflint.hcl)
        run: tflint --init
        env:
          # GitHub has rate limits for anonymous requests.
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Format
        run: terraform fmt -check
        # continue-on-error: true

      - name: Validate
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform bootstrap
        uses: ./.github/actions/terraform_bootstrap
        with:
          terraform_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform plan
        id: tfplan_step
        env:
          # no tfvars within runners. Add variables in repo var within github.
          TF_VAR_subnet_config: ${{ vars.TF_VAR_subnet_config }}
        run: | 
          # Only works if plan succeded
          # Cant create an readable file if failed.
          terraform plan -out=tfplan                     # Binary output
          terraform show -no-color tfplan > tfplan.txt   # Human readable output

      - name: Generate an artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-output
          path: tfplan.txt