name: Deploy deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform bootstrap
        uses: ./.github/actions/terraform_bootstrap
        with:
          terraform_token: ${{ secrets.TF_API_TOKEN}}

      - name: Terraform deploy
        env:
          # no tfvars within runners. Add variables in repo var within github.
          TF_VAR_subnet_config: ${{ vars.TF_VAR_subnet_config }}
        run: terraform destroy -auto-approve 