# Testing and performing terraform plan
name: Terraform testing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Initialization
        run: terraform init

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0

      - name: Initialize  TFLint
        # Downloads AWS plugin. (.tflint.hcl)
        run: tflint --init
        env:
          # GitHub has rate limits for anonymous requests.
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Format
        run: terraform fmt -check

      - name: Validate
        run: terraform validate